### ISSUE TITLE
Enable auto pull-requests for new Glean SDK releases 📦

### ISSUE THREAD

**Issue by hackebrot** [mozilla/burnham#71]
We unpinned the Glean SDK version in #67. The next step is to automatically build and push an updated burnham Docker image to GKE for new releases of the Python bindings on PyPI. We have configured CircleCI to build and push Docker images for pushes to the main branch. Can we add a requirements.txt file and set up Dependabot to automatically open pull-requests against that file for new releases of the Glean SDK? 🤖 

https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by jklukas** [comment]
That sounds like a reasonable approach. We use dependabot for several data infra projects, so it's familiar territory.

**Comment by jrbenny35** [comment]
Is Glean the only requirement that should be pinned in the requirements.txt? Just want to be sure

**Comment by hackebrot** [comment]
I don't have a strong preference as long as we get notified of new Glean SDK releases and can update the burnham Docker image on GKE by merging a pull-request rather than manually pushing a change to the setup. Happy for you to decide if we pin the other dependencies too, @jrbenny35! 👍 

```python
install_requires = [
    "click>=7.0",
    "glean-sdk>=32.3.1",
    "wrapt",
    "typing_extensions"
]
```

**Comment by jklukas** [comment]
At least from the Data Platform team perspective, it's generally considered best practice to pin all dependencies in `requirements.txt` and ensure that `requirements.txt` is used both for CI and for building Docker images. This leads to more stable behavior, since you're less likely to have a PR trigger a build that silently pulls in a newer dependency version that causes breakage unrelated to the content of the PR.

So, I'd encourage pinning all dependencies as part of this work.

**Comment by jrbenny35** [comment]
Got it, will pin all!
